### ISSUE TITLE
Helpers for groups/panel data

### ISSUE THREAD

**Issue by ClaytonJY** [tidymodels/recipes#166] opened 2018-07-11 21:08 UTC
Is there a way to apply one or more steps on a _per-group_ basis? Suppose we have panel data (surprise, surprise) and want to apply `step_lag` on each group, is there a trick to getting this to work now?

If not, I've got two ideas:
- add an argument to step template like `group` or `strata` that handles grouped-application in one spot
- add a step like `step_group()` or `step_stratify()` which acts like `dplyr::group_by()` in that following operations are applied per group. Would presumably then need `step_ungroup()`/`step_unstratify()` to revert to normal application. Might also be able to create a `group_by.recipe()` method, a `grouped_recipe` class, etc. to avoid new steps and use `group_by` very naturally?

From a UX perspective I'd lean towards the second; steps already have an awful lot of args, and mirroring `dplyr` would make this very easy on users.

**Comment by topepo** [comment] 2018-07-12 05:07
That's a good idea. It would be better to add it on a per-step function but that would also mean big changes to the api. 

This would be behind the devel list a bit so I'll leave it open (and hopefully get some discussion) and mark it as not-short-term.

**Comment by BenoitLondon** [comment] 2021-06-07 11:14
Hi, any plan on this?  that's a real blocker for me :(

For example step_mode/median/meanImpute would be very useful with a grouped version

**Comment by juliasilge** [comment] 2021-06-07 18:29
We don't have this on a near-term plan for development work but are interested in hearing about your use case and needs in order to prioritize this idea.

**Comment by vspinu** [comment] 2021-08-01 21:08
It's somewhat surprising that this issue is open for 3 years and its still not on a "near-term" plan. Isn't a group_by operation for data processing package is an obvious feature?

Adding to @ClaytonJY original 2 ideas of the implementation:

 - `step_group` whose `...` would expand to individual steps. Thus one get's a nested arrangements of steps
```R
data %>% 
  step_select(x, y, z) %>%
  step_group(step_lag(x),
             step_center(y)
             by = "z")
```

**Comment by BenoitLondon** [comment] 2021-08-02 11:38
> We don't have this on a near-term plan for development work but are interested in hearing about your use case and needs in order to prioritize this idea.

There are many use cases, most relevant I have now is for example you miss longitude/latitude for some rows of your dataset but you have country info. Imputing per country would make much more sense than globally...

**Comment by joeycouse** [comment] 2021-08-03 16:32
I'll third this issue. An example I'm facing is imputing the finish time of a race which is very track dependent. Imputing with a group mean for the track would make much more sense.

**Comment by jestover** [comment] 2021-10-14 20:32
Thanks @joeycouse!  Just to make sure I'm understanding correctly let me ask about a simple example.  If I demean a variable using dplyr it will obviously use the sample mean from the entire dataset.  If I use recipes and then split my data into a training set and a testing set then recipes will demean the training set using the sample mean from the training set and demean the testing set using the sample mean from the testing set?

**Comment by mitokic** [comment] 2021-11-01 22:18
This would be great for use in a dataset with multiple time series when building a global model of all time series (panel data). Right now you would have to build a custom recipe step to apply groupwise transformations. Please consider working on this feature!

**Comment by tedmoorman** [comment] 2021-11-17 20:29
This should've been created a long time ago. Looks like I'll have to create a custom step for my project. Bummer.

**Comment by StatsMatt** [comment] 2021-11-23 14:41
I have another use case. Let's say I am trying to predict which vehicles will repair using the make and model name. I can concatenate the make and model of my training set and use the repair percentage of that make and model as a numeric predictor (i.e. target encoding). So, I can group by make and model and calculate the mean of 1's and 0's for the repair percentage. I will most likely have unseen levels, so I will use this in combo with step_novel. Thanks.

**Comment by topepo** [comment] 2021-11-29 22:47
Regarding a global method to make all steps capable of running computations per group, IMO that's not a great design choice so we won't be doing it. 

However, there are a lot of cases where this might make sense. Panel data may be one. For me, I'd love to make a set of chemometrics steps for processing spectra or high-content screening data. It would make sense, in those instances, to be able to group by a set of columns. 

There are a few requests in the thread here that can already be accomplished without additional (overall) changes. 

* For imputing by groups, this can be done using `step_impute_linear()` or `step_bag_impute()` by passing the grouping variable to the `impute_with` argument. That will get you mean imputation by group.

* For concatenating data prior to `step_novel()`, this can be done via `step_mutate()`. 

* Effect encoding can already be done with any of the `step_lencode_*()` functions in the `embed` package. 

My suggestion: for specific features, start new GH issues with the motivation and and a worked, reproducible example of what you want. Responding at the end of an issue that proposed general changes isn't a good way to go about creating new features. 

There are going to be times where we decline. That's disappointing but ok; there are custom steps that can be created. `textrecipes` is a great example of this. We didn't have a structure to work with tokenized data and the author made one that works really well for the particular problem that he is trying to solve. We didn't add this universally since that didn't make sense. 

I'm going to close this and hope that more specific issues can be posted with more details. @ClaytonJY it would be great to outline what exactly you would want for panel data in particular.

**Closed by topepo** 2021-11-29 22:47 UTC
Labels: long term
