### ISSUE TITLE
`step_select()` causing model `fit()` to fail

### ISSUE THREAD

**Issue by cb12991** [tidymodels/recipes#958] opened 2022-04-15 15:41 UTC
## The problem

I'm trying to adjust the variables included in my model, but I receive the following error when trying to `fit()`:

``` r
#> Error in eval_tidy(env$formula[[2]], env$data): object '.' not found
````

I traced the error back to a `step_select()` step included in my recipe. In particular, The error procs in the `form_form()` call. Fitting the recipe without the `step_select()` works as expected. Full reprex below.

## Reproducible example

``` r
library(tidymodels)
tidymodels_prefer()

s <- initial_split(iris)

m <- linear_reg() %>% 
  set_engine(
    'lm'
  ) %>%
  set_mode(
    'regression'
  )

r <- recipe(Sepal.Width ~ ., data = training(s))

w <- workflow(r, m)

fit(w, training(s))
#> == Workflow [trained] ==========================================================
#> Preprocessor: Recipe
#> Model: linear_reg()
#> 
#> -- Preprocessor ----------------------------------------------------------------
#> 0 Recipe Steps
#> 
#> -- Model -----------------------------------------------------------------------
#> 
#> Call:
#> stats::lm(formula = ..y ~ ., data = data)
#> 
#> Coefficients:
#>       (Intercept)       Sepal.Length       Petal.Length        Petal.Width  
#>            1.8802             0.3322            -0.1869             0.7211  
#> Speciesversicolor   Speciesvirginica  
#>           -1.2456            -1.5139

r_select <- r %>%
  step_select(
    Species,
    Petal.Width
  )

w_select <- workflow(r_select, m)

fit(w_select, training(s))
#> Error in eval_tidy(env$formula[[2]], env$data): object '.' not found
```

<sup>Created on 2022-04-15 by the [reprex package](https://reprex.tidyverse.org) (v2.0.1)</sup>

<details style="margin-bottom:10px;">
<summary>
Session info
</summary>

``` r
sessioninfo::session_info()
#> - Session info ---------------------------------------------------------------
#>  setting  value
#>  version  R version 4.1.3 (2022-03-10)
#>  os       Windows 10 x64 (build 19042)
#>  system   x86_64, mingw32
#>  ui       RTerm
#>  language (EN)
#>  collate  English_United States.1252
#>  ctype    English_United States.1252
#>  tz       America/Chicago
#>  date     2022-04-15
#>  pandoc   2.11.4 @ C:/Users/grc3b/RStudio/bin/pandoc/ (via rmarkdown)
#> 
#> - Packages -------------------------------------------------------------------
#>  package      * version    date (UTC) lib source
#>  assertthat     0.2.1      2019-03-21 [1] CRAN (R 4.1.2)
#>  backports      1.4.1      2021-12-13 [1] CRAN (R 4.1.1)
#>  broom        * 0.8.0      2022-04-13 [1] CRAN (R 4.1.2)
#>  cachem         1.0.6      2021-08-19 [1] CRAN (R 4.1.1)
#>  class          7.3-20     2022-01-16 [1] CRAN (R 4.1.3)
#>  cli            3.2.0      2022-02-14 [1] CRAN (R 4.1.2)
#>  codetools      0.2-18     2020-11-04 [1] CRAN (R 4.1.3)
#>  colorspace     2.0-3      2022-02-21 [1] CRAN (R 4.1.2)
#>  conflicted     1.1.0      2021-11-26 [1] CRAN (R 4.1.2)
#>  crayon         1.5.1      2022-03-26 [1] CRAN (R 4.1.3)
#>  DBI            1.1.2      2021-12-20 [1] CRAN (R 4.1.2)
#>  dials        * 0.1.1      2022-04-06 [1] CRAN (R 4.1.3)
#>  DiceDesign     1.9        2021-02-13 [1] CRAN (R 4.1.2)
#>  digest         0.6.29     2021-12-01 [1] CRAN (R 4.1.2)
#>  dplyr        * 1.0.8      2022-02-08 [1] CRAN (R 4.1.2)
#>  ellipsis       0.3.2      2021-04-29 [1] CRAN (R 4.1.2)
#>  evaluate       0.15       2022-02-18 [1] CRAN (R 4.1.2)
#>  fansi          1.0.3      2022-03-24 [1] CRAN (R 4.1.2)
#>  fastmap        1.1.0      2021-01-25 [1] CRAN (R 4.1.2)
#>  foreach        1.5.2      2022-02-02 [1] CRAN (R 4.1.2)
#>  fs             1.5.2      2021-12-08 [1] CRAN (R 4.1.2)
#>  furrr          0.2.3      2021-06-25 [1] CRAN (R 4.1.2)
#>  future         1.24.0     2022-02-19 [1] CRAN (R 4.1.2)
#>  future.apply   1.8.1      2021-08-10 [1] CRAN (R 4.1.1)
#>  generics       0.1.2      2022-01-31 [1] CRAN (R 4.1.2)
#>  ggplot2      * 3.3.5      2021-06-25 [1] CRAN (R 4.1.0)
#>  globals        0.14.0     2020-11-22 [1] CRAN (R 4.1.1)
#>  glue           1.6.2      2022-02-24 [1] CRAN (R 4.1.2)
#>  gower          1.0.0      2022-02-03 [1] CRAN (R 4.1.2)
#>  GPfit          1.0-8      2019-02-08 [1] CRAN (R 4.1.2)
#>  gtable         0.3.0      2019-03-25 [1] CRAN (R 4.1.2)
#>  hardhat        0.2.0      2022-01-24 [1] CRAN (R 4.1.2)
#>  highr          0.9        2021-04-16 [1] CRAN (R 4.1.0)
#>  htmltools      0.5.2      2021-08-25 [1] CRAN (R 4.1.1)
#>  infer        * 1.0.0      2021-08-13 [1] CRAN (R 4.1.2)
#>  ipred          0.9-12     2021-09-15 [1] CRAN (R 4.1.0)
#>  iterators      1.0.14     2022-02-05 [1] CRAN (R 4.1.2)
#>  knitr          1.38       2022-03-25 [1] CRAN (R 4.1.2)
#>  lattice        0.20-45    2021-09-22 [1] CRAN (R 4.1.3)
#>  lava           1.6.10     2021-09-02 [1] CRAN (R 4.1.1)
#>  lhs            1.1.5      2022-03-22 [1] CRAN (R 4.1.3)
#>  lifecycle      1.0.1      2021-09-24 [1] CRAN (R 4.1.1)
#>  listenv        0.8.0      2019-12-05 [1] CRAN (R 4.1.1)
#>  lubridate      1.8.0      2021-10-07 [1] CRAN (R 4.1.1)
#>  magrittr       2.0.3      2022-03-30 [1] CRAN (R 4.1.3)
#>  MASS           7.3-55     2022-01-16 [1] CRAN (R 4.1.3)
#>  Matrix         1.4-0      2021-12-08 [1] CRAN (R 4.1.3)
#>  memoise        2.0.1      2021-11-26 [1] CRAN (R 4.1.2)
#>  modeldata    * 0.1.1      2021-07-14 [1] CRAN (R 4.1.2)
#>  munsell        0.5.0      2018-06-12 [1] CRAN (R 4.1.2)
#>  nnet           7.3-17     2022-01-16 [1] CRAN (R 4.1.3)
#>  parallelly     1.31.0     2022-04-07 [1] CRAN (R 4.1.3)
#>  parsnip      * 0.2.1      2022-03-17 [1] CRAN (R 4.1.3)
#>  pillar         1.7.0      2022-02-01 [1] CRAN (R 4.1.2)
#>  pkgconfig      2.0.3      2019-09-22 [1] CRAN (R 4.1.2)
#>  plyr           1.8.7      2022-03-24 [1] CRAN (R 4.1.2)
#>  pROC           1.18.0     2021-09-03 [1] CRAN (R 4.1.1)
#>  prodlim        2019.11.13 2019-11-17 [1] CRAN (R 4.1.2)
#>  purrr        * 0.3.4      2020-04-17 [1] CRAN (R 4.1.2)
#>  R.cache        0.15.0     2021-04-30 [1] CRAN (R 4.1.2)
#>  R.methodsS3    1.8.1      2020-08-26 [1] CRAN (R 4.1.1)
#>  R.oo           1.24.0     2020-08-26 [1] CRAN (R 4.1.1)
#>  R.utils        2.11.0     2021-09-26 [1] CRAN (R 4.1.1)
#>  R6             2.5.1      2021-08-19 [1] CRAN (R 4.1.1)
#>  Rcpp           1.0.8.3    2022-03-17 [1] CRAN (R 4.1.3)
#>  recipes      * 0.2.0      2022-02-18 [1] CRAN (R 4.1.2)
#>  reprex         2.0.1      2021-08-05 [1] CRAN (R 4.1.1)
#>  rlang          1.0.2      2022-03-04 [1] CRAN (R 4.1.2)
#>  rmarkdown      2.13       2022-03-10 [1] CRAN (R 4.1.3)
#>  rpart          4.1.16     2022-01-24 [1] CRAN (R 4.1.3)
#>  rsample      * 0.1.1      2021-11-08 [1] CRAN (R 4.1.2)
#>  rstudioapi     0.13       2020-11-12 [1] CRAN (R 4.1.2)
#>  scales       * 1.1.1      2020-05-11 [1] CRAN (R 4.1.2)
#>  sessioninfo    1.2.2      2021-12-06 [1] CRAN (R 4.1.2)
#>  stringi        1.7.6      2021-11-29 [1] CRAN (R 4.1.2)
#>  stringr        1.4.0      2019-02-10 [1] CRAN (R 4.1.0)
#>  styler         1.7.0      2022-03-13 [1] CRAN (R 4.1.3)
#>  survival       3.2-13     2021-08-24 [1] CRAN (R 4.1.3)
#>  tibble       * 3.1.6      2021-11-07 [1] CRAN (R 4.1.2)
#>  tidymodels   * 0.2.0      2022-03-19 [1] CRAN (R 4.1.3)
#>  tidyr        * 1.2.0      2022-02-01 [1] CRAN (R 4.1.2)
#>  tidyselect     1.1.2      2022-02-21 [1] CRAN (R 4.1.2)
#>  timeDate       3043.102   2018-02-21 [1] CRAN (R 4.1.1)
#>  tune         * 0.2.0      2022-03-19 [1] CRAN (R 4.1.3)
#>  utf8           1.2.2      2021-07-24 [1] CRAN (R 4.1.1)
#>  vctrs          0.4.1      2022-04-13 [1] CRAN (R 4.1.2)
#>  withr          2.5.0      2022-03-03 [1] CRAN (R 4.1.2)
#>  workflows    * 0.2.6      2022-03-18 [1] CRAN (R 4.1.3)
#>  workflowsets * 0.2.1      2022-03-15 [1] CRAN (R 4.1.2)
#>  xfun           0.30       2022-03-02 [1] CRAN (R 4.1.2)
#>  yaml           2.3.5      2022-02-21 [1] CRAN (R 4.1.2)
#>  yardstick    * 0.0.9      2021-11-22 [1] CRAN (R 4.1.2)
#> 
#>  [1] C:/Users/grc3b/R-4.1.3/library
#> 
#> ------------------------------------------------------------------------------
```

</details>

**Comment by EmilHvitfeldt** [comment] 2022-04-15 15:46
This is a duplicate of https://github.com/tidymodels/recipes/issues/741 and https://github.com/tidymodels/recipes/issues/937.

The current recommendation would be to use `update_role()` or `step_rm()` to deal with this problem.

**Comment by cb12991** [comment] 2022-04-15 16:03
Thanks. A workaround using `update_role()` resolved the error.

**Closed** 2022-04-15 16:09 UTC
