### ISSUE TITLE
Surprised not to see more step_{x} functions similar to functions in dplyr and base-r

### ISSUE THREAD

**Issue by tedmoorman** [tidymodels/recipes#857] opened 2021-11-18 18:51 UTC
## Feature
I'm working on a classification project using text narratives, which ends up being my initial exposure to the ``tidymodels`` ecosystem. I think the ``recipes`` preprocessor is a critical step to prevent data leakage from training to testing. I'm surprised to find that much of the functionality available in ``dplyr`` and ``base-r`` seems to be excluded from the ``recipes::step_{x}`` functions. Here's a short list of functions from these packages that I would be using right now, were they available.

From ``dplyr``:
``distinct()``, ``anti_join()``, ``count()``, ``summarise()``, ``group_by()``
From ``base-r``:
``%in%``, ``merge()``

In looking at [the source code](https://github.com/tidymodels/recipes/tree/main/R), the script for each ``recipes::step_{x}`` function appears lengthy and quite similar. I'm wondering if more ``recipes::step_{x}`` functions could be added by first creating a more general function for step function creation (for example, see [the customesteps package](https://cran.r-project.org/package=customsteps)) that could be quickly applied across many``dplyr``/``base-r`` functions. Otherwise, [the process for creating custom ``recipes::step_{x}`` functions](https://www.tidymodels.org/learn/develop/recipes/) looks too onerous for a lot of users.

**Comment by EmilHvitfeldt** [comment] 2021-11-18 19:13
The core goal of {recipes} is to provide feature engineering steps to get your data ready for modeling. The key term here is modeling. While {recipes} is created around modeling it can still be useful for general transformations that aren't modeling-related. This means that every transformation that is applied to the training data set, should be possible to reapply to new data. This is to make sure that we can correctly perform the right transformation within resampling folds, or just in general for future applications of the model workflow.

The functions you listed would be hard to incorporate into this framework as they summarise the observations rather than transform them. Ideally, when using a recipe you want the same number of rows returned from a recipe as you put into one. This is not to say that recipes steps can't change the number of observations, but it is mostly done as filtering or up/downsampling step. 

The process of creating a new step does involve a lot of boilerplate, and we are looking for ways to streamline the code needed to produce a step. But at the end of the day, there will still be some complexity we can't avoid. If you have some simple transformations you can use `step_mutate()` to apply your custom function.

If you have any specific use-case you need that you can't get working in {recipes} let us know and we help you with how to fit it into a recipe if possible.

**Comment by tedmoorman** [comment] 2021-11-18 20:21
> The core goal of {recipes} is to provide feature engineering steps to get your data ready for modeling. The key term here is modeling. While {recipes} is created around modeling it can still be useful for general transformations that aren't modeling-related. This means that every transformation that is applied to the training data set, should be possible to reapply to new data. This is to make sure that we can correctly perform the right transformation within resampling folds, or just in general for future applications of the model workflow.

My understanding, from looking at the documentation, is that the user can choose whether or not to reapply any transformation to the new data. For example, it looks like most of the step functions allow for `skip = TRUE` or `skip = FALSE`. I could imagine many cases in which it'll be important for users to apply transformations to both training data and new data. Please consider that there are also cases, such as the one I'm facing, in which it's important to have clarity and confidence about what fraction of the data each transformation is being applied to, in order to prevent data leakage. By explicitly designating whether transformations apply only to training data or also to new data, `recipes` offers a more robust framework for iteratively testing models within resampling folds than would otherwise be possible.

> The functions you listed would be hard to incorporate into this framework as they summarise the observations rather than transform them. Ideally, when using a recipe you want the same number of rows returned from a recipe as you put into one. This is not to say that recipes steps can't change the number of observations, but it is mostly done as filtering or up/downsampling step.

I'm glad you mention the use of `step_filter()`. The default value is `skip = TRUE` for that function. So, in that case, it appears to be expected that any filtering would only be applied to training data and not new data. For the functions I suggested, I wouldn't want the summarization/deduplication/transformation applied to new data, but it would be important to have it applied to the training data.

> The process of creating a new step does involve a lot of boilerplate, and we are looking for ways to streamline the code needed to produce a step. But at the end of the day, there will still be some complexity we can't avoid. If you have some simple transformations you can use `step_mutate()` to apply your custom function.

That's great that you're looking for ways to streamline the code for creating additional steps! Unfortunately, `step_mutate()` won't work in the case I'm considering.

> If you have any specific use-case you need that you can't get working in {recipes} let us know and we help you with how to fit it into a recipe if possible.

Thank you kindly for the offer, and for all your work on the package! At this point, I think I'll have to start working with [the custom steps package](https://cran.r-project.org/web/packages/customsteps/index.html).

**Comment by EmilHvitfeldt** [comment] 2021-11-18 20:42
You should be careful with using `skip = TRUE`  for anything that changes the number or names of the columns in a data set. The example below illustrates that. We are doing a simple PC Regression. It fits the model just fine. But when we go to predict with it it won't perform the PCA transformation and the logistic regression complains because It doesn't recognize the columns it is given. If you look you will see that `skip = TRUE` is mostly done on steps that change rows, not the columns.

``` r
library(tidymodels)

rec_spec <- recipe(mpg ~ ., data = mtcars) %>%
  step_pca(all_numeric_predictors(), skip = TRUE)

lm_spec <- linear_reg()

wf_spec <- workflow(rec_spec, lm_spec)

wf_fit <- fit(wf_spec, mtcars)

predict(wf_fit, mtcars)
#> Error: Can't subset columns that don't exist.
#> x Columns `PC1`, `PC2`, `PC3`, `PC4`, and `PC5` don't exist.
```

You mentioned that you working on a classification task using text narritives. If you haven't already, then I suggest you take a look at the {textrecipes} package https://textrecipes.tidymodels.org/.

**Comment by tedmoorman** [comment] 2021-11-19 14:27
> You should be careful with using `skip = TRUE` for anything that changes the number or names of the columns in a data set. The example below illustrates that. We are doing a simple PC Regression. It fits the model just fine. But when we go to predict with it it won't perform the PCA transformation and the linear regression complains because It doesn't recognize the columns it is given. If you look you will see that `skip = TRUE` is mostly done on steps that change rows, not the columns.
> 
> ```r
> library(tidymodels)
> 
> rec_spec <- recipe(mpg ~ ., data = mtcars) %>%
>   step_pca(all_numeric_predictors(), skip = TRUE)
> 
> lm_spec <- linear_reg()
> 
> wf_spec <- workflow(rec_spec, lm_spec)
> 
> wf_fit <- fit(wf_spec, mtcars)
> 
> predict(wf_fit, mtcars)
> #> Error: Can't subset columns that don't exist.
> #> x Columns `PC1`, `PC2`, `PC3`, `PC4`, and `PC5` don't exist.
> ```
Thank you for the warning about using `skip = TRUE`. In the case you presented, you would definitely want to also extract principal components _separately_ for the new data, since you were estimating the regressions coefficients for the principal components in the training data. So, `skip = FALSE` seems to be the obvious choice there. But, you wouldn't want to extract the principal components for the _combination_ of training data and new data, which is where the real value-add of the `recipes` package comes in.    
> You mentioned that you working on a classification task using text narritives. If you haven't already, then I suggest you take a look at the {textrecipes} package https://textrecipes.tidymodels.org/.
Thank you for mentioning the `textrecipes` package. For my particular application, I will be using the `step_tokenize()` function. Unfortunately, I then need to eliminate duplicate tokens, classify/associate tokens in the training data according to the outcome variable, and then classify the test data according to which outcome its tokens are associated with. And that's where I would need the functions from `dplyr` and `base-r` mentioned previously. While I'd prefer to keep everything simple and non-parametric, complexity could be increased by choosing a statistical cutoff (for example, less than or greater than 1 standard deviation from the mean token count) for classifying/associating tokens in the training data according to the outcome variable. The statistical cutoff could then be chosen optimally according to a performance metric from resampling folds.

**Comment by tedmoorman** [comment] 2021-11-19 22:56
I'm trying to modify some of the code used in the `customsteps` package. Everything seems to go fine until I have to modify the part of the code related to `bake`. Any suggestions? Please see [#3 requiring bake helper function when `skip = TRUE` ](https://github.com/smaakage85/customsteps/issues/3)

**Comment by topepo** [comment] 2021-11-22 15:24
You might consider using the recipe step [template](https://github.com/tidymodels/recipes/blob/main/inst/boilerplate.R) that is in recipes. You will need to namespace the functions in recipes (e.g. use `recipes::step()` instead of `step()`, etc.). 

I suspect that the error you mention above is related to some step component that you don't need. 

Also, about the original request, we want to avoid adding steps for all of the dplyr verbs, especially the join functions. For those, we would have to store the data set(s) being joined in the step, which can be problematic. Also, these are deterministic operations that can be done before using the recipe so there is no loss of functionality.

**Comment by tedmoorman** [comment] 2021-11-22 16:32
> You might consider using the recipe step [template](https://github.com/tidymodels/recipes/blob/main/inst/boilerplate.R) that is in recipes. You will need to namespace the functions in recipes (e.g. use `recipes::step()` instead of `step()`, etc.).
> 
> I suspect that the error you mention above is related to some step component that you don't need.
> 
Thanks for the tip. Instead of modifying the `step_custom_transformation_new` function, I may see if I can create another function in the `customsteps` package specifically for non-baked items, 
> Also, about the original request, we want to avoid adding steps for all of the dplyr verbs, especially the join functions. For those, we would have to store the data set(s) being joined in the step, which can be problematic. Also, these are deterministic operations that can be done before using the recipe so there is no loss of functionality.
>
I guess the problem I'm seeing with using join functions before using recipe is in applying the join functions to the resampling folds. After using a `vfold_cv`, I get a list of lists. It's hard to tell how that data is split up into training and testing data and how joins might be applied only to the training data within each resampling fold. With recipes, I don't really need to worry about any of that (for example, I'd just use `prepper`). 

It's true that I could simply apply the joins to the entire training data set, but then I lose the ability to perform cross-fold validation within the training data.

**Comment by EmilHvitfeldt** [comment] 2022-12-09 22:41
Thank you for filling the issue! This issue doens't have any actionable features to add to {recipes} and instead turned into some general questions and discussion. I'm closing this issue. If you have any further questions/feature requests feel free to open another issue.

**Closed by EmilHvitfeldt** 2022-12-09 22:41 UTC
