### ISSUE TITLE
Inverse transformations

### ISSUE THREAD

**Issue by krzjoa** [tidymodels/recipes#998] opened 2022-06-01 12:36 UTC
In the **scikit-learn** world, preprocessors such as [StandardScaler](https://scikit-learn.org/stable/modules/generated/sklearn.preprocessing.StandardScaler.html) or [LabelEncoder](https://scikit-learn.org/stable/modules/generated/sklearn.preprocessing.LabelEncoder.html#sklearn.preprocessing.LabelEncoder) have _inverse_transform_ method, which transforms the data back to the original representation.  It can be useful e.g. while working on classifcation task or regression with scaled target variable. For the latter one, scikit-learn has even a dedicated [TransformedTargetRegressor](https://scikit-learn.org/stable/modules/generated/sklearn.compose.TransformedTargetRegressor.html#sklearn.compose.TransformedTargetRegressor) class which facilitates building pipelines composed of regressor and two-way target/output transformation.

My proposal is to introduce an additional verb to easily handle such cases, say _invert_. It could work as shown below:

```r
library(recipes, warn.conflicts = FALSE)
#> Warning: package 'recipes' was built under R version 4.0.5
#> Loading required package: dplyr
#> Warning: replacing previous import 'vctrs::data_frame' by 'tibble::data_frame'
#> when loading 'dplyr'
#> 
#> Attaching package: 'dplyr'
#> The following objects are masked from 'package:stats':
#> 
#>     filter, lag
#> The following objects are masked from 'package:base':
#> 
#>     intersect, setdiff, setequal, union

iris_df <- as.data.frame(iris)

iris_recipe <- 
  recipe(Species ~ ., data = iris_df) %>% 
  step_normalize(all_numeric()) %>% 
  step_dummy(Species, one_hot = TRUE) %>% 
  prep()

(iris_df_transformed <-
  iris_recipe %>% 
  bake(new_data = iris_df))
#> # A tibble: 150 x 7
#>    Sepal.Length Sepal.Width Petal.Length Petal.Width Species_setosa
#>           <dbl>       <dbl>        <dbl>       <dbl>          <dbl>
#>  1       -0.898      1.02          -1.34       -1.31              1
#>  2       -1.14      -0.132         -1.34       -1.31              1
#>  3       -1.38       0.327         -1.39       -1.31              1
#>  4       -1.50       0.0979        -1.28       -1.31              1
#>  5       -1.02       1.25          -1.34       -1.31              1
#>  6       -0.535      1.93          -1.17       -1.05              1
#>  7       -1.50       0.786         -1.34       -1.18              1
#>  8       -1.02       0.786         -1.28       -1.31              1
#>  9       -1.74      -0.361         -1.34       -1.31              1
#> 10       -1.14       0.0979        -1.28       -1.44              1
#> # ... with 140 more rows, and 2 more variables: Species_versicolor <dbl>,
#> #   Species_virginica <dbl>

invert <- function(x, ...){
  UseMethod("invert")
}


invert.step <- function(x, data, ...) {
  rlang::abort(
    paste0(
      "No `invert` method for a step with classes: ",
      paste0(class(x), collapse = ", ")
    )
  )
}


invert.step_normalize <- function(x, data, ...){

  mapping <- Map(as.character, rlang::exprs(...))

  if (length(mapping) == 0) {
    .cols  <- names(x$means)
    mapping <- .cols
    names(mapping) <- .cols
  }
  
  # Column name
  cn <- function (x) mapping[[x]]

  data <- 
    data %>% 
    mutate(across(
      all_of(names(mapping)), 
      ~ .x  * x$sds[[cn(cur_column())]] + x$means[[cn(cur_column())]]
    ))
  
  data
}


invert(iris_recipe$steps[[1]], data = iris_df_transformed)
#> # A tibble: 150 x 7
#>    Sepal.Length Sepal.Width Petal.Length Petal.Width Species_setosa
#>           <dbl>       <dbl>        <dbl>       <dbl>          <dbl>
#>  1          5.1         3.5          1.4       0.2                1
#>  2          4.9         3            1.4       0.2                1
#>  3          4.7         3.2          1.3       0.2                1
#>  4          4.6         3.1          1.5       0.2                1
#>  5          5           3.6          1.4       0.2                1
#>  6          5.4         3.9          1.7       0.4                1
#>  7          4.6         3.4          1.4       0.3                1
#>  8          5           3.4          1.5       0.2                1
#>  9          4.4         2.9          1.4       0.2                1
#> 10          4.9         3.1          1.5       0.100              1
#> # ... with 140 more rows, and 2 more variables: Species_versicolor <dbl>,
#> #   Species_virginica <dbl>

(sample_df <- tibble(.pred = iris_df_transformed$Sepal.Width))
#> # A tibble: 150 x 1
#>      .pred
#>      <dbl>
#>  1  1.02  
#>  2 -0.132 
#>  3  0.327 
#>  4  0.0979
#>  5  1.25  
#>  6  1.93  
#>  7  0.786 
#>  8  0.786 
#>  9 -0.361 
#> 10  0.0979
#> # ... with 140 more rows

invert(iris_recipe$steps[[1]], data = sample_df, .pred = Sepal.Width)
#> # A tibble: 150 x 1
#>    .pred
#>    <dbl>
#>  1   3.5
#>  2   3  
#>  3   3.2
#>  4   3.1
#>  5   3.6
#>  6   3.9
#>  7   3.4
#>  8   3.4
#>  9   2.9
#> 10   3.1
#> # ... with 140 more rows
Created on 2022-06-01 by the reprex package (v2.0.1)
```

**Comment by EmilHvitfeldt** [comment] 2022-06-01 16:34
Hello @krzjoa, Thanks for making an issue and showing interest in the project! This feature request is a duplicate of https://github.com/tidymodels/recipes/issues/155 and https://github.com/tidymodels/recipes/issues/264. Summarized below

> This will eventually be a post-processor in workflows. You shouldn't do this in recipes since the full recipe results are given to the model. Untransforming needs to happen after the model is fit.

**Comment by EmilHvitfeldt** [comment] 2022-06-01 22:54
No need to worry! I'm going to close this issue like the others as we will do this once we get to post-processing.

**Closed by EmilHvitfeldt** 2022-06-01 22:54 UTC
