### ISSUE TITLE
step_rm(skip=TRUE) not working with bake() leading predict() to fail

### ISSUE THREAD

**Issue by AndrewKostandy** [tidymodels/recipes#239] opened 2018-11-05 00:11 UTC
The skip = TRUE argument of step_rm() doesn't seem to work with bake() as the variable still gets removed from the baked dataset. Additionally, the predict() function throws an error despite the fact that the removed variable isn't really needed in the model and the interaction that involved that variable, and is needed by the model, is available in the dataset to be predicted on.

``` r
library(tidyverse)
library(recipes)
library(caret)

rec_1 <- recipe(Species ~ ., data = iris) %>% 
  step_interact(terms = ~ Sepal.Length:Sepal.Width) %>% 
  step_rm(Sepal.Length, skip = TRUE)

train_ctrl <- trainControl(method = "none", classProbs = TRUE)

rf_1 <- train(rec_1, data=iris, method = "rf", trControl = train_ctrl)
#> Loading required namespace: randomForest

prep_rec <- prep(rec_1, iris, retain=TRUE)

iris_juiced <- juice(prep_rec)

iris_baked <- bake(prep_rec, newdata = iris)

colnames(iris_juiced)
#> [1] "Sepal.Width"                "Petal.Length"              
#> [3] "Petal.Width"                "Species"                   
#> [5] "Sepal.Length_x_Sepal.Width"

colnames(iris_baked)
#> [1] "Sepal.Width"                "Petal.Length"              
#> [3] "Petal.Width"                "Species"                   
#> [5] "Sepal.Length_x_Sepal.Width"

predict(rf_1, iris_juiced, type = "response")
#> Error in eval(predvars, data, env): object 'Sepal.Length' not found

predict(rf_1, iris_baked, type = "response")
#> Error in eval(predvars, data, env): object 'Sepal.Length' not found
```

<sup>Created on 2018-11-05 by the [reprex package](https://reprex.tidyverse.org) (v0.2.1)</sup>
<details><summary>Session info</summary>

``` r
devtools::session_info()
#> ─ Session info ──────────────────────────────────────────────
#>  setting  value                       
#>  version  R version 3.5.1 (2018-07-02)
#>  os       macOS High Sierra 10.13.6   
#>  system   x86_64, darwin15.6.0        
#>  ui       X11                                
#> 
#> ─ Packages ──────────────────────────────────────────────
#>  package      * version    date       lib
#>  tidyverse    * 1.2.1      2017-11-14 [1]
#>  recipes      * 0.1.3.9002 2018-10-26 [1]
#>  caret        * 6.0-80     2018-05-26 [1]
```
</details>

**Comment by topepo** [comment] 2018-11-05 01:32
Internally, the step is skipped. The issue is that the list of variables that should be retained after processing the steps is defined in `bake.recipes` as:

```r
keepers <- terms_select(terms = terms, info = object$term_info)
``` 
where `object$term_info` holds the information about what variables were available at the end of `prep.recipes`. In this case:

```r
> object$term_info
# A tibble: 1 x 4
  variable type    role      source  
  <chr>    <chr>   <chr>     <chr>   
1 x2       numeric predictor original
```
because that was all that was left after prepping the recipes. Clearly wrong in this case so we'll need to think this though.

**Comment by topepo** [comment] 2018-11-06 18:32
I think that the line
```r
keepers <- terms_select(terms = terms, info = object$term_info)
```

needs to occur _after_ `newdata` is computed and, instead of `object$term_info` as the context, use `newdata`.

**Comment by topepo** [comment] 2018-11-12 21:55
> If my understanding is correct, this would keep the variable after using bake if `skip=TRUE`. But why does `predict()` still need the variable to be present in the data despite that it was removed at the end of the recipe and isn't used in the model?

It was used in the model since the skip only affects the processing of _new_ data (via `bake`). To get the processed version of the training set, `caret` uses `juice` so it will be there and not in the set of new data being predicted using `bake`. It is intended for cases where you need to affect the outcome data but avoid errors in processing new samples (since you won't have the outcome in hand).

**Comment by topepo** [comment] 2018-11-12 22:01
I'll merge in a fix for this in a minute. Here is what things look like after the changes:

``` r
library(tidyverse)
library(recipes)
#> 
#> Attaching package: 'recipes'
#> The following object is masked from 'package:stringr':
#> 
#>     fixed
#> The following object is masked from 'package:stats':
#> 
#>     step
library(caret)
#> Loading required package: lattice
#> 
#> Attaching package: 'caret'
#> The following object is masked from 'package:purrr':
#> 
#>     lift

rec_1 <- recipe(Species ~ ., data = iris) %>% 
  step_interact(terms = ~ Sepal.Length:Sepal.Width) %>% 
  step_rm(Sepal.Length, skip = TRUE)

train_ctrl <- trainControl(method = "none", classProbs = TRUE)

rf_1 <- train(rec_1, data=iris, method = "rf", trControl = train_ctrl)
#> Loading required namespace: randomForest

prep_rec <- prep(rec_1, iris, retain=TRUE)

iris_juiced <- juice(prep_rec)

iris_baked <- bake(prep_rec, newdata = iris)

colnames(iris_juiced)
#> [1] "Sepal.Width"                "Petal.Length"              
#> [3] "Petal.Width"                "Species"                   
#> [5] "Sepal.Length_x_Sepal.Width"

colnames(iris_baked)
#> [1] "Sepal.Length"               "Sepal.Width"               
#> [3] "Petal.Length"               "Petal.Width"               
#> [5] "Species"                    "Sepal.Length_x_Sepal.Width"
```

Created on 2018-11-12 by the [reprex package](https://reprex.tidyverse.org) (v0.2.1)

**Closed** 2018-11-12 22:59 UTC
Labels: bug, reprex

**Comment by AndrewKostandy** [comment] 2018-11-13 10:05
Works great! Thank you Max.
